name: convnext_base_trimodal
embed_dim: 768
d_model: 768
dropout: 0.3
use_layer_norm: true
head_hidden: [1024, 512]
backbone:
  pretrained: true
  freeze: false
  unfreeze_last: 2
tabular_encoder:
  name: mlp
  dropout: 0.3
  hidden: 256
